### ISSUE TITLE
Desktopl-patch 

### ISSUE THREAD

**Issue by SaicharanKandukuri** [1X1-Tech/Toolloa#6]
Needed suggestion and review for [**desktopl-patch**](https://github.com/1X1-Tech/Toolloa/tree/Desktopl-patch)
All good pull requests, suggestions, and tweaking ideas are welcome!

**Comment by shiv123shiv123** [comment]
I give some suggestion according to error occured while i install desktopl tweaked version.
- you should replace link for .tar.gz file for distro plugins i.e this https://build.nethunter.com/kalifs/kalifs-latest/kalifs-armhf-minimal.tar.xz because it have 2019 version which after installation huge update will give, i used another distro plugin sofware of another app `anlinux`
- One big issue occure during installation that stop my installation process in between because i says `you have no key `some key here`-- i handle this error after adding this line in you desktopl.sh file `apt-key adv --keyserver  hkp://keys.gnupg.net --recv-keys 7D8D0BF6` after adding this line whole process going smoothly without any error occure.
- Thanks

**Comment by SaicharanKandukuri** [comment]
Thanks for the suggestion 
- Problem 2 is fixed in the Desktopl-patch branch !
https://github.com/1X1-Tech/Toolloa/tree/Desktopl-patch
e9f9860 
- As problem 2 is linked with 1 Latest kali builds will be available soon! 
1. desktopl
2. nethunter

Thank you @shiv123shiv123  for letting me know

**Comment by SaicharanKandukuri** [comment]
A new update to stop over time consumption for the installation is coming soon
version v0.3
